server:
  port: 9998

spring:
  application:
    name: book-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true

